### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by RatakondalaArun** [fluttercommunity/flutter_launcher_icons#379]
- [x] Web #348 
- [x] #380
- [ ] #378 
- [ ] Add MacOS support
- [ ] Add Linux(Snap Store) support 
  - (https://github.com/flutter/flutter/issues/53229)
- [ ] Refactor Android and IOS to support New Schema
  - ([373](https://github.com/fluttercommunity/flutter_launcher_icons/issues/373))
- [ ] #373 

**Good to have**
- [ ] Run FLI commands with `flutter pub run flutter_launcher_icons` instead of `flutter pub run flutter_launcher_icons:main`
- [ ] Generate `flutter_launcher_icons.yaml` config file with `flutter pub run flutter_launcher_icons generate`
- [ ] Add `.pub_ignore` to ignore unrelated folders like `test`
- [ ] Support for dynamic icons

**Comment by RatakondalaArun** [comment]
@MarkOSullivan94 @bradintheusa 

Please feel free to edit this list

**Comment by MarkOSullivan94** [comment]
@RatakondalaArun I think it's time to publish a new release and test out the GitHub action for automatically deploying a new release to Pub

Think it's good to update to `0.10.0` for this release and then any bug fixes will be `0.10.x`.

Want open a PR with all the necessary changes (`pubspec.yaml`, `README.md`, `CHANGELOG.md`) and then we can test it out?

**Comment by RatakondalaArun** [comment]
I think we need to fix #384 before the release of `v0.10.0`. All new projects are affected by this issue.

**Comment by RatakondalaArun** [comment]
@MarkOSullivan94 #384 is fixed in #253

**Comment by RatakondalaArun** [comment]
> Want open a PR with all the necessary changes (pubspec.yaml, README.md, CHANGELOG.md) and then we can test it out?

Is there any way to automate these updates? The way I see we have most of the info
- `pubspec.yaml`: We can get the `package` version from the GitHub release tag
- `CHANGELOG.md`: we can get the changelog from the GitHub release tag description
- `README.md`: these get updated when needed by a feature release

**Comment by MarkOSullivan94** [comment]
**1. CHANGELOG.md**

I've noticed there's a nice new feature when publishing new GitHub releases that automatically generates a change log so that would take care of `CHANGELOD.md`

**2. pubspec.yaml /  versioning**

For versioning we could suggest for contributors to use [cider](https://pub.dev/packages/cider) - I haven't used it before but it looks like it should fit our use case.

We need to bump the version **before** publishing a new GitHub release due to our CD pipeline where we try to automatically publish a new version to pub with GitHub Actions because we'll run into issues trying to republish the same version

**3. README.md**

Perhaps this is one for us to pay attention to during the PR process or maybe have a template for new PRs which encourage people to update the README.md if it's introducing a new feature, what do you think @RatakondalaArun?

**Comment by MarkOSullivan94** [comment]
@RatakondalaArun I deleted the old published release because it didn't upload to Pub due to x3 failing tests, you can see these here: https://github.com/fluttercommunity/flutter_launcher_icons/actions/runs/2798119853

The `package_version_test.dart` was failing because build runner wasn't run to update the generated package version, I've fixed that and amended the last commit and then forced pushed

Since then I've published another `v0.10.0` which has triggered the action and we have all of the tests passing now but it has failed the dry run: https://github.com/fluttercommunity/flutter_launcher_icons/runs/7683629796

**Comment by RatakondalaArun** [comment]
> Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 2.12.0-0, consider publishing the package as a pre-release instead.
>   See https://dart.dev/tools/pub/publishing#publishing-prereleases For more information on pre-releases

We need to update pubspec.yaml

https://github.com/fluttercommunity/flutter_launcher_icons/blob/23fb8b371e24e81a18c024bb2f21f46049b082b9/pubspec.yaml#L16-L18

**Comment by MarkOSullivan94** [comment]
> > Packages with an SDK constraint on a pre-release of the Dart SDK should themselves be published as a pre-release version. If this package needs Dart version 2.12.0-0, consider publishing the package as a pre-release instead.
> > See https://dart.dev/tools/pub/publishing#publishing-prereleases For more information on pre-releases
> 
> We need to update pubspec.yaml
> 
> https://github.com/fluttercommunity/flutter_launcher_icons/blob/23fb8b371e24e81a18c024bb2f21f46049b082b9/pubspec.yaml#L16-L18

Updated `pubspec.yaml` and amended the last commit, the GitHub action ran successfully and v0.10.0 is now publicly available 🥳

**Comment by RatakondalaArun** [comment]
Great🎉 I also created a milestone for next release https://github.com/fluttercommunity/flutter_launcher_icons/milestone/2

**Comment by MarkOSullivan94** [comment]
@RatakondalaArun we should prioritise both #401 and #402 to ensure flutter_launcher_icons is receiving the best possible score from [pub.dev](https://pub.dev/)

**Comment by RatakondalaArun** [comment]
@MarkOSullivan94 Let's release a new version with support for `macos` and a few fixes

**Comment by sirwes** [comment]
Can we put auto generating adaptive icons on this list?

**Comment by OutdatedGuy** [comment]
@MarkOSullivan94, the `Add .pub_ignore to ignore unrelated folders like test` task is done right? If yes, please tick it here

**Comment by MarkOSullivan94** [comment]
@OutdatedGuy yep that's done, ticked it now, thanks for pointing that out

**Comment by OutdatedGuy** [comment]
@MarkOSullivan94 can you tick generate config file task.

**Comment by MarkOSullivan94** [comment]
Done thanks @OutdatedGuy

**Comment by MarkOSullivan94** [comment]
Added https://github.com/fluttercommunity/flutter_launcher_icons/issues/466 to the roadmap as a good to have
